name: Run Twitter Bot

on:

  schedule:
    - cron: "0 1 * * *"    # 06:30 IST
    - cron: "10 1 * * *"   # 06:40 IST
    - cron: "20 1 * * *"   # 06:50 IST
    - cron: "30 13 * * *"  # 19:00 IST
    - cron: "40 13 * * *"  # 19:10 IST
    - cron: "50 13 * * *"  # 19:20 IST
    - cron: "30 19 * * *"  # 01:00 IST
    - cron: "40 19 * * *"  # 01:10 IST
    - cron: "50 19 * * *"  # 01:20 IST
    - cron: "30 3 * * *"   # 08:30 IST
    - cron: "0 7 * * *"    # 13:00 IST
    - cron: "30 10 * * *"  # 16:30 IST

  workflow_dispatch: {} # Manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Bot
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: python3 auto_poster.py
